name: PART_3-FIGURES_2_3_4
description: "Running Agent H and Agent A on the joint 7x7 maze gridworld, discount rate = 0.1, reward correlation = 0. 10,000 reward samples."
program: sweep.py
parameters:
  joint_mdp_graph:
    value:
      "joint_7x7_gridworld_maze"
  seed_policy_graph_agent_A:
    value:
      "joint_7x7_gridworld_maze_agent_A_uniform_random"
  discount_rate:
    value:
      0.1
  discount_rate_agent_A:
    value:
      0.1
  reward_distribution:
    value:
      default_dist:
        dist_name:
          "uniform"
        params:
          [0, 1]
      allow_all_equal_rewards:
        False
  reward_correlation:
    value:
      0
  num_reward_samples:
    value:
      10000
  convergence_threshold:
    value:
      0.0001
  num_workers:
    value:
      10
  random_seed:
    value:
      0
