name: PART_1-FIGURE_1
description: "Running a single agent on the 3x3 gridworld, with gamma = 0.6. 50,000 reward samples."
program: sweep.py
parameters:
  mdp_graph:
    value:
      "3x3_gridworld"
  discount_rate:
    value:
      0.6
  reward_distribution:
    value:
      default_dist:
        dist_name:
          "uniform"
        params:
          [0, 1]
      allow_all_equal_rewards:
        False
  num_reward_samples:
    value:
      50000
  convergence_threshold:
    value:
      0.0001
  num_workers:
    value:
      10
  random_seed:
    value:
      0
