name: test_sweep_gridworld
description: "Sweeping over discount rates on the 3x3 gridworld with self-loops at each cell."
program: sweep.py
parameters:
  mdp_graph:
    value:
      "gridworld_selfloop_3x3"
  discount_rate:
    values:
      - 0.3
      - 0.6
      - 0.9
    names:
      - "0p3"
      - "0p6"
      - "0p9"
  reward_distribution:
    value:
      default_dist:
        dist_name:
          "uniform"
        params:
          [0, 1]
  num_reward_samples:
    value:
      10000
  convergence_threshold:
    value:
      0.0001
  num_workers:
    value:
      10
  random_seed:
    value:
      0
