name: test_sweep_correlated_rewards
description: "Sweeping over Agent A and Agent B reward correlation values on the 3x3 multiagent gridworld, with gamma = 0.2."
program: sweep.py
parameters:
  joint_mdp_graph:
    value:
      "joint_3x3_gridworld"
  seed_policy_graph_agent_B:
    value:
      "joint_3x3_gridworld_agent_B_uniform_random"
  discount_rate:
    value:
      0.2
  discount_rate_agent_B:
    value:
      0.2
  reward_distribution:
    value:
      default_dist:
        dist_name:
          "uniform"
        params:
          [0, 1]
      allow_all_equal_rewards:
        False
  reward_correlation:
    values:
      - 1
      - 0
      - -1
    names:
      - "1"
      - "0"
      - "n1"
  num_reward_samples:
    value:
      10000
  convergence_threshold:
    value:
      0.0001
  num_workers:
    value:
      10
  random_seed:
    value:
      0
